### ISSUE TITLE
Classes that don't have Acc or AP in the name aren't factored into GPA

### ISSUE THREAD

**Issue by ghost** [menai/PowerGPA#28]
Probably unfixable, but for example Science Research 1 is one of my classes that gives Acc credit, but Acc isn't part of its name, so I doubt that can be deduced - as it is now, my grade from that class doesn't show up in the window and also isn't factored into the final GPA.

**Comment by maclover7** [comment]
Thank you for reporting. Investigating a solution.

**Comment by maclover7** [comment]
Should be fixed by #39.
