### ISSUE TITLE
Nondescript error found when trying to calculate GPA

### ISSUE THREAD

**Issue by AbhinavMadahar** [menai/PowerGPA#46]
![screen shot 2016-11-04 at 8 58 10 am](https://cloud.githubusercontent.com/assets/8312336/20006411/cb8e6070-a26d-11e6-8145-27ad4aa2ef14.png)

My username and password are correct, and I selected "Student" and left the powerschool URL to its default (ps2.millburn.org). It worked for me yesterday, but broke just now

**Comment by maclover7** [comment]
Should be fixed by #47.
