### ISSUE TITLE
missing a course in Q1 GPA

### ISSUE THREAD

**Issue by zhengfangchen** [menai/PowerGPA#57]
Dear Power GPA admin,

My login ID is zhengfangchen, I am a parent; I logged in to my child's GPA calculation for Q1 Millburn High School, the GPA is missing Honors Portfolio Dev, is there a reason why this course is not included? if this is a mistake, could you please forward to the right team to fix this issu?

Thanks,

Jennifer

**Comment by maclover7** [comment]
Hi @zhengfangchen! I just pushed a fix to the site, can you confirm that it is now working as expected?
